FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build
WORKDIR /app
COPY . ./
RUN dotnet restore
RUN dotnet publish -c Release -o out

FROM mcr.microsoft.com/dotnet/aspnet:7.0
ENV ASPNETCORE_URLS=http://+:5000
WORKDIR /app
COPY --from=build /app/out .
ENTRYPOINT ["dotnet", "MqttSubscriber.dll"]